// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/100steps/gin-layout/controller"
	"github.com/100steps/gin-layout/cron"
	"github.com/100steps/gin-layout/middleware"
	"github.com/100steps/gin-layout/service"
)

import (
	_ "github.com/100steps/gin-layout/dao/migration"
)

// Injectors from wire.go:

func initApp() (*app, error) {
	userService := service.NewUserService()
	middlewareMiddleware := middleware.NewMiddleware(userService)
	cronCron := cron.NewCron()
	userController := controller.NewUserController(userService)
	mainApp := newApp(middlewareMiddleware, cronCron, userController)
	return mainApp, nil
}
